services:
  server:
    build:
      context: ./backend
    ports:
      - 8000:8000
  client:
    build:
      context: ./client
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
